### ISSUE TITLE
Symbol not found: ___addtf3

### ISSUE THREAD

**Issue by xiaoxi99cs** [citwild/laugh-finder#11]
Hi Guys,

Anyone   seen this error ? How did u fix it? 

ImportError: dlopen(/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/linalg/_fblas.cpython-36m-darwin.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/linalg/../.dylibs/libquadmath.0.dylib
  Expected in: /usr/local/lib/libgcc_s.1.dylib
 in /Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/linalg/../.dylibs/libquadmath.0.dylib
(laughenv) rockmac:python-training rock$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from file_feature_extraction import file_feature_extraction
  File "/Users/rock/laugh/laugh-finder/python-training/file_feature_extraction.py", line 1, in <module>
    import scipy.io.wavfile as wavfile
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/io/__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/io/matlab/miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/misc/__init__.py", line 53, in <module>
    from scipy.interpolate._pade import pade
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/interpolate/__init__.py", line 176, in <module>
    from .interpolate import *
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 20, in <module>
    import scipy.linalg
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/linalg/__init__.py", line 175, in <module>
    from .misc import *
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/linalg/blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: dlopen(/Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/linalg/_fblas.cpython-36m-darwin.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/linalg/../.dylibs/libquadmath.0.dylib
  Expected in: /usr/local/lib/libgcc_s.1.dylib
 in /Users/rock/laugh/laugh-finder/python-training/laughenv/lib/python3.6/site-packages/scipy/linalg/../.dylibs/libquadmath.0.dylib

Thanks
Rock

**Comment by MilesDowe** [comment]
Hi Rock,

Thanks for bringing up this issue!

I'm not entirely certain, but I suspect this is an issue with the setup of scipy. Googling your specific issue 
(`__addtf3`) brought up a handful of issues that seem to have been resolved through updating/reinstalling scipy packages.

- https://stackoverflow.com/questions/31667876/failed-scipy-special-import-symbol-not-found-addtf3
- https://github.com/yosinski/deep-visualization-toolbox/issues/104
- https://github.com/scipy/scipy/issues/5093

Let me know if those leads aren't helpful or if you continue to have issues. If you are able to resolve it, please supply me any details and I'll gladly update the README.

**Comment by ens-lg4** [comment]
It took me almost a week to find the real cause behind this ImportError.

So I'd like to share my humble analysis for others who might hit the same thing again.

The **___addtf3** symbol is a GCC software floating point function. It is used by scipy indirectly, and sometimes the order of search paths on your system does not let the right library to be found.

With the help of "nm" utility I have searched my system for dynamic libraries that contain the **definition** of this function and it happened to be in /usr/local/opt/gcc/lib/gcc/7/libgcc_ext.10.4.dylib (I installed my gcc-7 using brew) . Your mileage may vary, but most likely you need to find where your GCC libraries live.

My DYLD_LIBRARY_PATH initially contained "/usr/lib", and I tried both prepending and appending the newly found path /usr/local/opt/gcc/lib/gcc/7 to the old path.

Appending did not have any effect at all. However, prepending solved the ImportError, which means there must be some kind of red herring in /usr/lib that was preventing the correct operation.

**Comment by intheravine** [comment]
Hmm - I'm not sure why my /usr/local/lib/libgcc_s.1.dylib was from 2008 and was not updated with updates to my machine. I updated it by hand - hopefully I haven't messed something else up but now radian works.

**Comment by jhsenjaliya** [comment]
I had system gcc at `/usr/bin/gcc` and removing `/usr/bin` from `DYLD_LIBRARY_PATH` worked for me ( on Catalina mac OS). Thanks Leo Gordon ( @ens-lg4 ) for sharing.

**Comment by izakharkin** [comment]
**UPD**: Solved, the details are [here](https://stackoverflow.com/questions/66015218/loading-dylib-in-python-fails-on-macos-big-sur-symbol-not-found-addtf3).

@ens-lg4 appreciate your help very much, but the approach you proposed does not work for me, unfortunately :(

I am trying to load some custom `mylib.dylib` with python3.7 on Mac OS X Big Sur 11.1 and it gives me this error:
```
OSError                                   Traceback (most recent call last)
<ipython-input-7-21ad9f6d803b> in <module>
     12 try:
---> 13     mylib = ctypes.CDLL(mylib_path)
     14 except OSError:

~/opt/anaconda3/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:

OSError: dlopen(mylib.dylib, 6): Symbol not found: ___addtf3
  Referenced from: /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib
  Expected in: flat namespace
 in /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib
 ```
 
 `nm` of `/usr/local/opt/gcc/lib/gcc/10/libgcc_ext.10.4.dylib` shows that it containts `__addtf3` exactly, but setting `DYLD_LIBRARY_PATH` does not affect at all. I tried: 
 - `export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/opt/gcc/lib/gcc/10/`
 - `export DYLD_LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/10/:$DYLD_LIBRARY_PATH`
 - In python script: `os.environ['DYLD_LIBRARY_PATH'] = "/usr/local/opt/gcc/lib/gcc/10/"`
 - In `~/opt/anaconda3/lib/python3.7/ctypes/macholib/dyld.py`: have tried to change the values of `DEFAULT_FRAMEWORK_FALLBACK` and `DEFAULT_LIBRARY_FALLBACK` variables accordingly
 
I also tried to set the path to `libgcc_ext.10.4.dylib` in `libquadmath.0.dylib`:
```
install_name_tool -change /usr/lib/libSystem.B.dylib /usr/local/opt/gcc/lib/gcc/10/libgcc_ext.10.4.dylib /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib
``` 
It might help because there is no `/usr/lib/libSystem.B.dylib` on Big Sur 11.1 (so this file is not used I suppose), but instead it gives me a new error:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-21ad9f6d803b> in <module>
     12 try:
---> 13     mylib = ctypes.CDLL(mylib_path)
     14 except OSError:

~/opt/anaconda3/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:

OSError: dlopen(mylib.dylib, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/10/libgcc_ext.10.4.dylib
  Referenced from: /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib
  Reason: no suitable image found.  Did find:
	/usr/local/opt/gcc/lib/gcc/10/libgcc_ext.10.4.dylib: mach-o, but wrong filetype
	/usr/local/Cellar/gcc/10.2.0/lib/gcc/10/libgcc_ext.10.4.dylib: mach-o, but wrong filetype
```

I am quite new to all this dynamic linking stuff, so any advice and thoughts would be highly appreciated  🙏
